/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Decoder, DecoderInterface } from "../../contracts/Decoder";

const _abi = [
  {
    inputs: [],
    name: "CalldataOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cfa2e24ff33bb48749a8c39ec454c8819e0b10d229bc45c8b1a4910446a5531164736f6c63430008110033";

type DecoderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DecoderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Decoder__factory extends ContractFactory {
  constructor(...args: DecoderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Decoder> {
    return super.deploy(overrides || {}) as Promise<Decoder>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Decoder {
    return super.attach(address) as Decoder;
  }
  override connect(signer: Signer): Decoder__factory {
    return super.connect(signer) as Decoder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DecoderInterface {
    return new utils.Interface(_abi) as DecoderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Decoder {
    return new Contract(address, _abi, signerOrProvider) as Decoder;
  }
}
