/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ICustomConditionInterface extends utils.Interface {
  functions: {
    "check(uint256,bytes,uint256,uint256,bytes12)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "check"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "check",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;

  events: {};
}

export interface ICustomCondition extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICustomConditionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    check(
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      location: PromiseOrValue<BigNumberish>,
      size: PromiseOrValue<BigNumberish>,
      extra: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; reason: string }>;
  };

  check(
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    location: PromiseOrValue<BigNumberish>,
    size: PromiseOrValue<BigNumberish>,
    extra: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { success: boolean; reason: string }>;

  callStatic: {
    check(
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      location: PromiseOrValue<BigNumberish>,
      size: PromiseOrValue<BigNumberish>,
      extra: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; reason: string }>;
  };

  filters: {};

  estimateGas: {
    check(
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      location: PromiseOrValue<BigNumberish>,
      size: PromiseOrValue<BigNumberish>,
      extra: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    check(
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      location: PromiseOrValue<BigNumberish>,
      size: PromiseOrValue<BigNumberish>,
      extra: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
