/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type UnwrappedTransactionStruct = {
  operation: PromiseOrValue<BigNumberish>;
  to: PromiseOrValue<string>;
  value: PromiseOrValue<BigNumberish>;
  dataLocation: PromiseOrValue<BigNumberish>;
  dataSize: PromiseOrValue<BigNumberish>;
};

export type UnwrappedTransactionStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  operation: number;
  to: string;
  value: BigNumber;
  dataLocation: BigNumber;
  dataSize: BigNumber;
};

export interface ITransactionUnwrapperInterface extends utils.Interface {
  functions: {
    "unwrap(address,uint256,bytes,uint8)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "unwrap"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "unwrap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;

  events: {};
}

export interface ITransactionUnwrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITransactionUnwrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    unwrap(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [UnwrappedTransactionStructOutput[]] & {
        result: UnwrappedTransactionStructOutput[];
      }
    >;
  };

  unwrap(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    operation: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<UnwrappedTransactionStructOutput[]>;

  callStatic: {
    unwrap(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<UnwrappedTransactionStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    unwrap(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    unwrap(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
