/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockConsumptions } from "./MockConsumptions";
export type { MockDecoder } from "./MockDecoder";
export type { MockIntegrity } from "./MockIntegrity";
export type { MultiSend } from "./MultiSend";
export type { TestAvatar } from "./TestAvatar";
export type { TestContract } from "./TestContract";
export type { TestCustomChecker } from "./TestCustomChecker";
export type { TestEncoder } from "./TestEncoder";
