/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type ConsumptionStruct = {
  allowanceKey: PromiseOrValue<BytesLike>;
  balance: PromiseOrValue<BigNumberish>;
  consumed: PromiseOrValue<BigNumberish>;
};

export type ConsumptionStructOutput = [string, BigNumber, BigNumber] & {
  allowanceKey: string;
  balance: BigNumber;
  consumed: BigNumber;
};

export interface MockConsumptionsInterface extends utils.Interface {
  functions: {
    "merge((bytes32,uint128,uint128)[],(bytes32,uint128,uint128)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "merge"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "merge",
    values: [ConsumptionStruct[], ConsumptionStruct[]]
  ): string;

  decodeFunctionResult(functionFragment: "merge", data: BytesLike): Result;

  events: {};
}

export interface MockConsumptions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockConsumptionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    merge(
      c1: ConsumptionStruct[],
      c2: ConsumptionStruct[],
      overrides?: CallOverrides
    ): Promise<
      [ConsumptionStructOutput[]] & { result: ConsumptionStructOutput[] }
    >;
  };

  merge(
    c1: ConsumptionStruct[],
    c2: ConsumptionStruct[],
    overrides?: CallOverrides
  ): Promise<ConsumptionStructOutput[]>;

  callStatic: {
    merge(
      c1: ConsumptionStruct[],
      c2: ConsumptionStruct[],
      overrides?: CallOverrides
    ): Promise<ConsumptionStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    merge(
      c1: ConsumptionStruct[],
      c2: ConsumptionStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    merge(
      c1: ConsumptionStruct[],
      c2: ConsumptionStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
