/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface WriteOnceInterface extends utils.Interface {
  functions: {
    "SALT()": FunctionFragment;
    "SINGLETON_FACTORY()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "SALT" | "SINGLETON_FACTORY"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "SALT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SINGLETON_FACTORY",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "SALT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SINGLETON_FACTORY",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WriteOnce extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WriteOnceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SALT(overrides?: CallOverrides): Promise<[string]>;

    SINGLETON_FACTORY(overrides?: CallOverrides): Promise<[string]>;
  };

  SALT(overrides?: CallOverrides): Promise<string>;

  SINGLETON_FACTORY(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SALT(overrides?: CallOverrides): Promise<string>;

    SINGLETON_FACTORY(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    SALT(overrides?: CallOverrides): Promise<BigNumber>;

    SINGLETON_FACTORY(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SALT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SINGLETON_FACTORY(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
