/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type ConditionFlatStruct = {
  parent: PromiseOrValue<BigNumberish>;
  paramType: PromiseOrValue<BigNumberish>;
  operator: PromiseOrValue<BigNumberish>;
  compValue: PromiseOrValue<BytesLike>;
};

export type ConditionFlatStructOutput = [number, number, number, string] & {
  parent: number;
  paramType: number;
  operator: number;
  compValue: string;
};

export interface IntegrityInterface extends utils.Interface {
  functions: {
    "enforce((uint8,uint8,uint8,bytes)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "enforce"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "enforce",
    values: [ConditionFlatStruct[]]
  ): string;

  decodeFunctionResult(functionFragment: "enforce", data: BytesLike): Result;

  events: {};
}

export interface Integrity extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IntegrityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    enforce(
      conditions: ConditionFlatStruct[],
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  enforce(
    conditions: ConditionFlatStruct[],
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    enforce(
      conditions: ConditionFlatStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    enforce(
      conditions: ConditionFlatStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    enforce(
      conditions: ConditionFlatStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
