/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type ConditionFlatStruct = {
  parent: PromiseOrValue<BigNumberish>;
  paramType: PromiseOrValue<BigNumberish>;
  operator: PromiseOrValue<BigNumberish>;
  compValue: PromiseOrValue<BytesLike>;
};

export type ConditionFlatStructOutput = [number, number, number, string] & {
  parent: number;
  paramType: number;
  operator: number;
  compValue: string;
};

export interface PermissionBuilderInterface extends utils.Interface {
  functions: {
    "allowFunction(bytes32,address,bytes4,uint8)": FunctionFragment;
    "allowTarget(bytes32,address,uint8)": FunctionFragment;
    "allowances(bytes32)": FunctionFragment;
    "avatar()": FunctionFragment;
    "disableModule(address,address)": FunctionFragment;
    "enableModule(address)": FunctionFragment;
    "execTransactionFromModule(address,uint256,bytes,uint8)": FunctionFragment;
    "execTransactionFromModuleReturnData(address,uint256,bytes,uint8)": FunctionFragment;
    "getGuard()": FunctionFragment;
    "getModulesPaginated(address,uint256)": FunctionFragment;
    "guard()": FunctionFragment;
    "isModuleEnabled(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeFunction(bytes32,address,bytes4)": FunctionFragment;
    "revokeTarget(bytes32,address)": FunctionFragment;
    "scopeFunction(bytes32,address,bytes4,(uint8,uint8,uint8,bytes)[],uint8)": FunctionFragment;
    "scopeTarget(bytes32,address)": FunctionFragment;
    "setAllowance(bytes32,uint128,uint128,uint128,uint64,uint64)": FunctionFragment;
    "setAvatar(address)": FunctionFragment;
    "setGuard(address)": FunctionFragment;
    "setTarget(address)": FunctionFragment;
    "setUp(bytes)": FunctionFragment;
    "target()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowFunction"
      | "allowTarget"
      | "allowances"
      | "avatar"
      | "disableModule"
      | "enableModule"
      | "execTransactionFromModule"
      | "execTransactionFromModuleReturnData"
      | "getGuard"
      | "getModulesPaginated"
      | "guard"
      | "isModuleEnabled"
      | "owner"
      | "renounceOwnership"
      | "revokeFunction"
      | "revokeTarget"
      | "scopeFunction"
      | "scopeTarget"
      | "setAllowance"
      | "setAvatar"
      | "setGuard"
      | "setTarget"
      | "setUp"
      | "target"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowFunction",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "allowTarget",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "allowances",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "avatar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disableModule",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableModule",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModule",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModuleReturnData",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "getGuard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getModulesPaginated",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "guard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isModuleEnabled",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeFunction",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTarget",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeFunction",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      ConditionFlatStruct[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeTarget",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowance",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvatar",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setGuard",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTarget",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUp",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "avatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModuleReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getModulesPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAvatar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGuard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AllowFunction(bytes32,address,bytes4,uint8)": EventFragment;
    "AllowTarget(bytes32,address,uint8)": EventFragment;
    "AvatarSet(address,address)": EventFragment;
    "ChangedGuard(address)": EventFragment;
    "DisabledModule(address)": EventFragment;
    "EnabledModule(address)": EventFragment;
    "ExecutionFromModuleFailure(address)": EventFragment;
    "ExecutionFromModuleSuccess(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RevokeFunction(bytes32,address,bytes4)": EventFragment;
    "RevokeTarget(bytes32,address)": EventFragment;
    "ScopeFunction(bytes32,address,bytes4,tuple[],uint8)": EventFragment;
    "ScopeTarget(bytes32,address)": EventFragment;
    "SetAllowance(bytes32,uint128,uint128,uint128,uint64,uint64)": EventFragment;
    "TargetSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllowFunction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowTarget"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AvatarSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangedGuard"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisabledModule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnabledModule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionFromModuleFailure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionFromModuleSuccess"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeFunction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeTarget"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScopeFunction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScopeTarget"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAllowance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TargetSet"): EventFragment;
}

export interface AllowFunctionEventObject {
  roleKey: string;
  targetAddress: string;
  selector: string;
  options: number;
}
export type AllowFunctionEvent = TypedEvent<
  [string, string, string, number],
  AllowFunctionEventObject
>;

export type AllowFunctionEventFilter = TypedEventFilter<AllowFunctionEvent>;

export interface AllowTargetEventObject {
  roleKey: string;
  targetAddress: string;
  options: number;
}
export type AllowTargetEvent = TypedEvent<
  [string, string, number],
  AllowTargetEventObject
>;

export type AllowTargetEventFilter = TypedEventFilter<AllowTargetEvent>;

export interface AvatarSetEventObject {
  previousAvatar: string;
  newAvatar: string;
}
export type AvatarSetEvent = TypedEvent<[string, string], AvatarSetEventObject>;

export type AvatarSetEventFilter = TypedEventFilter<AvatarSetEvent>;

export interface ChangedGuardEventObject {
  guard: string;
}
export type ChangedGuardEvent = TypedEvent<[string], ChangedGuardEventObject>;

export type ChangedGuardEventFilter = TypedEventFilter<ChangedGuardEvent>;

export interface DisabledModuleEventObject {
  module: string;
}
export type DisabledModuleEvent = TypedEvent<
  [string],
  DisabledModuleEventObject
>;

export type DisabledModuleEventFilter = TypedEventFilter<DisabledModuleEvent>;

export interface EnabledModuleEventObject {
  module: string;
}
export type EnabledModuleEvent = TypedEvent<[string], EnabledModuleEventObject>;

export type EnabledModuleEventFilter = TypedEventFilter<EnabledModuleEvent>;

export interface ExecutionFromModuleFailureEventObject {
  module: string;
}
export type ExecutionFromModuleFailureEvent = TypedEvent<
  [string],
  ExecutionFromModuleFailureEventObject
>;

export type ExecutionFromModuleFailureEventFilter =
  TypedEventFilter<ExecutionFromModuleFailureEvent>;

export interface ExecutionFromModuleSuccessEventObject {
  module: string;
}
export type ExecutionFromModuleSuccessEvent = TypedEvent<
  [string],
  ExecutionFromModuleSuccessEventObject
>;

export type ExecutionFromModuleSuccessEventFilter =
  TypedEventFilter<ExecutionFromModuleSuccessEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RevokeFunctionEventObject {
  roleKey: string;
  targetAddress: string;
  selector: string;
}
export type RevokeFunctionEvent = TypedEvent<
  [string, string, string],
  RevokeFunctionEventObject
>;

export type RevokeFunctionEventFilter = TypedEventFilter<RevokeFunctionEvent>;

export interface RevokeTargetEventObject {
  roleKey: string;
  targetAddress: string;
}
export type RevokeTargetEvent = TypedEvent<
  [string, string],
  RevokeTargetEventObject
>;

export type RevokeTargetEventFilter = TypedEventFilter<RevokeTargetEvent>;

export interface ScopeFunctionEventObject {
  roleKey: string;
  targetAddress: string;
  selector: string;
  conditions: ConditionFlatStructOutput[];
  options: number;
}
export type ScopeFunctionEvent = TypedEvent<
  [string, string, string, ConditionFlatStructOutput[], number],
  ScopeFunctionEventObject
>;

export type ScopeFunctionEventFilter = TypedEventFilter<ScopeFunctionEvent>;

export interface ScopeTargetEventObject {
  roleKey: string;
  targetAddress: string;
}
export type ScopeTargetEvent = TypedEvent<
  [string, string],
  ScopeTargetEventObject
>;

export type ScopeTargetEventFilter = TypedEventFilter<ScopeTargetEvent>;

export interface SetAllowanceEventObject {
  allowanceKey: string;
  balance: BigNumber;
  maxBalance: BigNumber;
  refillAmount: BigNumber;
  refillInterval: BigNumber;
  refillTimestamp: BigNumber;
}
export type SetAllowanceEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  SetAllowanceEventObject
>;

export type SetAllowanceEventFilter = TypedEventFilter<SetAllowanceEvent>;

export interface TargetSetEventObject {
  previousTarget: string;
  newTarget: string;
}
export type TargetSetEvent = TypedEvent<[string, string], TargetSetEventObject>;

export type TargetSetEventFilter = TypedEventFilter<TargetSetEvent>;

export interface PermissionBuilder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PermissionBuilderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowances(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        refillAmount: BigNumber;
        maxBalance: BigNumber;
        refillInterval: BigNumber;
        balance: BigNumber;
        refillTimestamp: BigNumber;
      }
    >;

    avatar(overrides?: CallOverrides): Promise<[string]>;

    disableModule(
      prevModule: PromiseOrValue<string>,
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enableModule(
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execTransactionFromModule(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execTransactionFromModuleReturnData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getGuard(overrides?: CallOverrides): Promise<[string] & { _guard: string }>;

    getModulesPaginated(
      start: PromiseOrValue<string>,
      pageSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], string] & { array: string[]; next: string }>;

    guard(overrides?: CallOverrides): Promise<[string]>;

    isModuleEnabled(
      _module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    scopeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      conditions: ConditionFlatStruct[],
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    scopeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAllowance(
      key: PromiseOrValue<BytesLike>,
      balance: PromiseOrValue<BigNumberish>,
      maxBalance: PromiseOrValue<BigNumberish>,
      refillAmount: PromiseOrValue<BigNumberish>,
      refillInterval: PromiseOrValue<BigNumberish>,
      refillTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAvatar(
      _avatar: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTarget(
      _target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUp(
      initializeParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    target(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  allowFunction(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    selector: PromiseOrValue<BytesLike>,
    options: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowTarget(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    options: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowances(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      refillAmount: BigNumber;
      maxBalance: BigNumber;
      refillInterval: BigNumber;
      balance: BigNumber;
      refillTimestamp: BigNumber;
    }
  >;

  avatar(overrides?: CallOverrides): Promise<string>;

  disableModule(
    prevModule: PromiseOrValue<string>,
    module: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enableModule(
    module: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execTransactionFromModule(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    operation: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execTransactionFromModuleReturnData(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    operation: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getGuard(overrides?: CallOverrides): Promise<string>;

  getModulesPaginated(
    start: PromiseOrValue<string>,
    pageSize: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string[], string] & { array: string[]; next: string }>;

  guard(overrides?: CallOverrides): Promise<string>;

  isModuleEnabled(
    _module: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeFunction(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    selector: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeTarget(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  scopeFunction(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    selector: PromiseOrValue<BytesLike>,
    conditions: ConditionFlatStruct[],
    options: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  scopeTarget(
    roleKey: PromiseOrValue<BytesLike>,
    targetAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAllowance(
    key: PromiseOrValue<BytesLike>,
    balance: PromiseOrValue<BigNumberish>,
    maxBalance: PromiseOrValue<BigNumberish>,
    refillAmount: PromiseOrValue<BigNumberish>,
    refillInterval: PromiseOrValue<BigNumberish>,
    refillTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAvatar(
    _avatar: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGuard(
    _guard: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTarget(
    _target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUp(
    initializeParams: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  target(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowances(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        refillAmount: BigNumber;
        maxBalance: BigNumber;
        refillInterval: BigNumber;
        balance: BigNumber;
        refillTimestamp: BigNumber;
      }
    >;

    avatar(overrides?: CallOverrides): Promise<string>;

    disableModule(
      prevModule: PromiseOrValue<string>,
      module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    enableModule(
      module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    execTransactionFromModule(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    execTransactionFromModuleReturnData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; returnData: string }>;

    getGuard(overrides?: CallOverrides): Promise<string>;

    getModulesPaginated(
      start: PromiseOrValue<string>,
      pageSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], string] & { array: string[]; next: string }>;

    guard(overrides?: CallOverrides): Promise<string>;

    isModuleEnabled(
      _module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      conditions: ConditionFlatStruct[],
      options: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAllowance(
      key: PromiseOrValue<BytesLike>,
      balance: PromiseOrValue<BigNumberish>,
      maxBalance: PromiseOrValue<BigNumberish>,
      refillAmount: PromiseOrValue<BigNumberish>,
      refillInterval: PromiseOrValue<BigNumberish>,
      refillTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAvatar(
      _avatar: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTarget(
      _target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUp(
      initializeParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    target(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AllowFunction(bytes32,address,bytes4,uint8)"(
      roleKey?: null,
      targetAddress?: null,
      selector?: null,
      options?: null
    ): AllowFunctionEventFilter;
    AllowFunction(
      roleKey?: null,
      targetAddress?: null,
      selector?: null,
      options?: null
    ): AllowFunctionEventFilter;

    "AllowTarget(bytes32,address,uint8)"(
      roleKey?: null,
      targetAddress?: null,
      options?: null
    ): AllowTargetEventFilter;
    AllowTarget(
      roleKey?: null,
      targetAddress?: null,
      options?: null
    ): AllowTargetEventFilter;

    "AvatarSet(address,address)"(
      previousAvatar?: PromiseOrValue<string> | null,
      newAvatar?: PromiseOrValue<string> | null
    ): AvatarSetEventFilter;
    AvatarSet(
      previousAvatar?: PromiseOrValue<string> | null,
      newAvatar?: PromiseOrValue<string> | null
    ): AvatarSetEventFilter;

    "ChangedGuard(address)"(guard?: null): ChangedGuardEventFilter;
    ChangedGuard(guard?: null): ChangedGuardEventFilter;

    "DisabledModule(address)"(module?: null): DisabledModuleEventFilter;
    DisabledModule(module?: null): DisabledModuleEventFilter;

    "EnabledModule(address)"(module?: null): EnabledModuleEventFilter;
    EnabledModule(module?: null): EnabledModuleEventFilter;

    "ExecutionFromModuleFailure(address)"(
      module?: PromiseOrValue<string> | null
    ): ExecutionFromModuleFailureEventFilter;
    ExecutionFromModuleFailure(
      module?: PromiseOrValue<string> | null
    ): ExecutionFromModuleFailureEventFilter;

    "ExecutionFromModuleSuccess(address)"(
      module?: PromiseOrValue<string> | null
    ): ExecutionFromModuleSuccessEventFilter;
    ExecutionFromModuleSuccess(
      module?: PromiseOrValue<string> | null
    ): ExecutionFromModuleSuccessEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RevokeFunction(bytes32,address,bytes4)"(
      roleKey?: null,
      targetAddress?: null,
      selector?: null
    ): RevokeFunctionEventFilter;
    RevokeFunction(
      roleKey?: null,
      targetAddress?: null,
      selector?: null
    ): RevokeFunctionEventFilter;

    "RevokeTarget(bytes32,address)"(
      roleKey?: null,
      targetAddress?: null
    ): RevokeTargetEventFilter;
    RevokeTarget(roleKey?: null, targetAddress?: null): RevokeTargetEventFilter;

    "ScopeFunction(bytes32,address,bytes4,tuple[],uint8)"(
      roleKey?: null,
      targetAddress?: null,
      selector?: null,
      conditions?: null,
      options?: null
    ): ScopeFunctionEventFilter;
    ScopeFunction(
      roleKey?: null,
      targetAddress?: null,
      selector?: null,
      conditions?: null,
      options?: null
    ): ScopeFunctionEventFilter;

    "ScopeTarget(bytes32,address)"(
      roleKey?: null,
      targetAddress?: null
    ): ScopeTargetEventFilter;
    ScopeTarget(roleKey?: null, targetAddress?: null): ScopeTargetEventFilter;

    "SetAllowance(bytes32,uint128,uint128,uint128,uint64,uint64)"(
      allowanceKey?: null,
      balance?: null,
      maxBalance?: null,
      refillAmount?: null,
      refillInterval?: null,
      refillTimestamp?: null
    ): SetAllowanceEventFilter;
    SetAllowance(
      allowanceKey?: null,
      balance?: null,
      maxBalance?: null,
      refillAmount?: null,
      refillInterval?: null,
      refillTimestamp?: null
    ): SetAllowanceEventFilter;

    "TargetSet(address,address)"(
      previousTarget?: PromiseOrValue<string> | null,
      newTarget?: PromiseOrValue<string> | null
    ): TargetSetEventFilter;
    TargetSet(
      previousTarget?: PromiseOrValue<string> | null,
      newTarget?: PromiseOrValue<string> | null
    ): TargetSetEventFilter;
  };

  estimateGas: {
    allowFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowances(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    avatar(overrides?: CallOverrides): Promise<BigNumber>;

    disableModule(
      prevModule: PromiseOrValue<string>,
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enableModule(
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execTransactionFromModule(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execTransactionFromModuleReturnData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getGuard(overrides?: CallOverrides): Promise<BigNumber>;

    getModulesPaginated(
      start: PromiseOrValue<string>,
      pageSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guard(overrides?: CallOverrides): Promise<BigNumber>;

    isModuleEnabled(
      _module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    scopeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      conditions: ConditionFlatStruct[],
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    scopeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAllowance(
      key: PromiseOrValue<BytesLike>,
      balance: PromiseOrValue<BigNumberish>,
      maxBalance: PromiseOrValue<BigNumberish>,
      refillAmount: PromiseOrValue<BigNumberish>,
      refillInterval: PromiseOrValue<BigNumberish>,
      refillTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAvatar(
      _avatar: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTarget(
      _target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUp(
      initializeParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    target(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowances(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avatar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disableModule(
      prevModule: PromiseOrValue<string>,
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enableModule(
      module: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionFromModule(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionFromModuleReturnData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getGuard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getModulesPaginated(
      start: PromiseOrValue<string>,
      pageSize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    guard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isModuleEnabled(
      _module: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    scopeFunction(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      conditions: ConditionFlatStruct[],
      options: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    scopeTarget(
      roleKey: PromiseOrValue<BytesLike>,
      targetAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAllowance(
      key: PromiseOrValue<BytesLike>,
      balance: PromiseOrValue<BigNumberish>,
      maxBalance: PromiseOrValue<BigNumberish>,
      refillAmount: PromiseOrValue<BigNumberish>,
      refillInterval: PromiseOrValue<BigNumberish>,
      refillTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAvatar(
      _avatar: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTarget(
      _target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUp(
      initializeParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    target(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
